add canvas trigger function for tools
kiddom/react-sketch pull request #23
Opened 2022-04-18 20:59 UTC by ruirui19

Add canvas trigger event to monitor when drawing on mouse up

Ticket: 
https://kiddom.atlassian.net/browse/CE-231?atlOrigin=eyJpIjoiMGY0ZDc5NTk5MzVjNDA0ZGJjOTk2YTM2NDI1YWExM2IiLCJwIjoiaiJ9

2022-04-18 23:07 UTC, nguyen-dunn commented on src/circle.js
> +    canvas.trigger("object:modified", { target: this.line });
@ruirui19 
this.circle not line correct?

2022-04-18 23:07 UTC, nguyen-dunn commented on src/rectangle.js
> +    canvas.trigger("object:modified", { target: this.line });
@ruirui19 
this.rect not line correct?

2022-04-18 23:07 UTC, nguyen-dunn commented on package-lock.json
> +  "version": "0.11.2",
I think this version is wrong it should be at least 4 or 5

2022-04-18 23:08 UTC, nguyen-dunn requested changes
@ruirui19 I think the version is wrong for this version and other comments

2022-04-18 23:24 UTC, ruirui19 commented on package-lock.json
> +  "version": "0.11.2",
I pull the latest master and the current version is 0.11.2..but somehow the package-lock file is not updated

2022-04-19 21:19 UTC, nguyen-dunn approved these changes
👍

2022-04-19 21:57 UTC, merged